---
# SMTP configuration, depends on VM host or SMTP credentials
EDXAPP_EMAIL_HOST: "%%EDXAPP_EMAIL_HOST%%"
EDXAPP_EMAIL_HOST_USER: "%%EDXAPP_EMAIL_HOST_USER%%"
EDXAPP_EMAIL_HOST_PASSWORD: "%%EDXAPP_EMAIL_HOST_PASSWORD%%"
EDXAPP_EMAIL_PORT: %%EDXAPP_EMAIL_PORT%%
EDXAPP_EMAIL_USE_TLS: %%EDXAPP_EMAIL_USE_TLS%%

# Database connections - need to confirm connection strings
ORA_MYSQL_HOST: "127.0.0.1"
XQUEUE_MYSQL_HOST: "127.0.0.1"
EDXAPP_MYSQL_HOST: "127.0.0.1"
EDXAPP_MEMCACHE: ["127.0.0.1:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS:
  - "127.0.0.1"
EDXAPP_MONGO_HOSTS: ["127.0.0.1"]
EDXAPP_MONGO_USE_SSL: False

# Configure discussion forum settings
FORUM_SINATRA_ENV: "development"
FORUM_RACK_ENV: "development"
FORUM_MONGO_DATABASE: "cs_comments_service"
FORUM_MONGO_PORT: "27017"
FORUM_MONGO_TAGS: !!null
MONGO_REPLICASET_NAME: ""

# Configure mongo database
EDXAPP_MONGO_USER: '%%MONGO_USER%%'
EDXAPP_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'

MONGO_USERS:
  - user: cs_comments_service
    password: password
    database: cs_comments_service
    roles: readWrite
  - user: edxapp
    password: password
    database: edxapp
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite

# Configure forum user, password and connection string
FORUM_MONGO_USER: '%%MONGO_USER%%'
FORUM_MONGO_PASSWORD: '%%MONGO_PASSWORD%%'
FORUM_MONGO_URL: "mongodb://{{ FORUM_MONGO_USER }}:{{ FORUM_MONGO_PASSWORD }}@{%- for host in FORUM_MONGO_HOSTS -%}{{ host }}:{{ FORUM_MONGO_PORT }}{%- if not loop.last -%},{%- endif -%}{%- endfor -%}/{{ FORUM_MONGO_DATABASE }}?replicaSet={{ MONGO_REPLICASET_NAME }}{%- if FORUM_MONGO_TAGS -%}&tags={{ FORUM_MONGO_TAGS }}{%- endif -%}"

# Configure mysql database
EDXAPP_MYSQL_USER_ADMIN: '%%MYSQL_ADMIN_USER%%'
EDXAPP_MYSQL_PASSWORD_ADMIN: '%%MYSQL_ADMIN_PASSWORD%%'
EDXAPP_MYSQL_USER: '%%MYSQL_USER%%'
EDXAPP_MYSQL_PASSWORD: '%%MYSQL_PASSWORD%%'

# Configure DNS for site and email links
EDXAPP_LMS_SITE_NAME: "%%LMS_URL%%"
EDXAPP_CMS_SITE_NAME: "%%CMS_URL%%"
EDXAPP_PREVIEW_SITE_NAME: "%%PREVIEW_URL%%"
EDXAPP_LMS_BASE: "{{ EDXAPP_LMS_SITE_NAME }}"
EDXAPP_CMS_BASE: "{{ EDXAPP_CMS_SITE_NAME }}"
EDXAPP_SITE_NAME: "{{ EDXAPP_LMS_SITE_NAME }}"

EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443

EDXAPP_LMS_PREVIEW_NGINX_PORT: 18020
EDXAPP_LMS_PREVIEW_SSL_NGINX_PORT: 48020
EDXAPP_LMS_PREVIEW_SSL_NGINX_FRONTEND_PORT: 443

EDXAPP_CMS_NGINX_PORT: 18010
EDXAPP_CMS_SSL_NGINX_PORT: 48010
EDXAPP_CMS_SSL_NGINX_FRONTEND_PORT: 443

NGINX_ENABLE_SSL: %%NGINX_ENABLE_SSL%%

EDXAPP_PYTHON_SANDBOX: false

ECOMMERCE_VERSION: "%%EDX_VERSION%%"
ECOMMERCE_WORKER_VERSION: "%%EDX_VERSION%%"

# Fix for TASK: [programs | create nodeenv] failed: "/edx/app/programs/venvs/programs/bin/nodeenv" not found
PROGRAMS_VERSION: "%%EDX_VERSION%%"

EDXAPP_CSRF_COOKIE_SECURE: false
